global:
  message: welcome to global Microservices application Environment!
logging:  
  level:
    root: INFO
management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh
  endpoint:      
    health:
      show-details: always
    info:
      enabled: true
