global:
  message: welcome to global Microservices application Environment!
logging:  
  level:
    root: INFO
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/    
management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh
  endpoint:      
    health:
      show-details: always
    info:
      enabled: true
