global:
  message: welcome to dev Microservices application Environment!
seerver:    
  port: 8082
message:
  welcome: Hello from Dev!
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cust_dev
    username: root
    password: root
  jpa:  
    hibernate:
      ddl-auto: update
    show-sql: true
